const data = {
  products: [
    {
      name: 'Signature Bianco Matte Ceramic Subway Wall Tile - 4 x 8 in.',
      slug: 'signature-bianco-matte-ceramic-subway-wall-tile',
      category: 'Signature Tile',
      image: '/images/product1.jpeg',
      price: 8.49,
      countInStock: 10,
      brand: 'Bianco',
      rating: 4.5,
      numReviews: 10,
      description: 'Matte subway wall tile',
    },
    {
      name: 'Riad White Ceramic Wall Tile - 4 x 4 in.',
      slug: 'riad-white-ceramic-wall-tile',
      category: 'Bathroom Tile',
      image: '/images/product2.jpeg',
      price: 12.69,
      countInStock: 10,
      brand: 'Riad',
      rating: 4.5,
      numReviews: 8,
      description: 'Moroccan-inspired white ceramic wall tile',
    },
    {
      name: 'Mallorca White Ceramic Wall Tile - 2.5 x 8 in.',
      slug: 'mallorca-white-ceramic-wall-tile',
      category: 'Fireplace Tile',
      image: '/images/product3.jpeg',
      price: 11.79,
      countInStock: 10,
      brand: 'Mallorca',
      rating: 4.5,
      numReviews: 10,
      description: 'Pearlescent subway wall tile',
    },
    {
      name: 'Kasbah Star Bone Porcelain Wall and Floor Tile - 6.5 x 6.5 in.',
      slug: 'kasbah-star-bone-porcelain-wall-and-floor-tile',
      category: 'Pool Tile',
      image: '/images/product4.jpeg',
      price: 13.19,
      countInStock: 10,
      brand: 'Kasbah',
      rating: 4.5,
      numReviews: 10,
      description: 'Moroccan Zellige porcelain wall and floor tile',
    },
  ],
};
export default data;
